services:

  backend:
    build: ./apps
    restart: always
    links:
      - db
    ports:
      - "3000"
    volumes:
      - app-data:/apps/public/images
  db:
    images: "maria db"
    restart: always
    links:
      - dbms
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=training
      - MYSQL_USER=peserta
      - MYSQL_PASSWORD=password
    volumes:
      - ./apps/database/:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql 


dbms:
  images: "phpmyadmin"
  restart: always
  ports:
    - "8001:80"
  enviroment:
    - PMA_HOST=db

web:
  build: ./nginx
  restart: always
  ports:
  - "80:80"
  depends_on:
    - backend

volumes:
  app-data:
  db-data:
